version: "3.8"

services:
  app1:
    build: ./app
    environment:
      - PORT=3000
      - INSTANCE=app1

  app2:
    build: ./app
    environment:
      - PORT=3000
      - INSTANCE=app2

  nginx:
    image: nginx:latest
    
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app1
      - app2
